### ISSUE TITLE
Structure of patching dataset

### ISSUE THREAD

**Issue by ShaileshSridhar2403** [mlfoundations/patching#1]
Hi loved the work!

I am trying to apply patching to a different dataset, is there any documentation regarding the structure of the input patching dataset?
If not could you please describe it?

Thanks!

**Comment by gabrielilharco** [comment]
Hi @ShaileshSridhar2403, thanks for the kind words!

There are some examples of datasets in this codebase in `src/datasets`, like [MNIST](https://github.com/mlfoundations/patching/blob/main/src/datasets/mnist.py).

The data loaders we create are pretty standard (so you can use datasets from torchvision, for instance), with the exception that you need to have the names for every category in your dataset (so CLIP knows how to create text embeddings for them). The way this is set in our codebase is through the `.classnames` attribute (e.g. see [here](https://github.com/mlfoundations/patching/blob/main/src/datasets/mnist.py#L41)).
You might also want to set up custom templates for your dataset, see [here](https://github.com/mlfoundations/patching/blob/main/src/datasets/templates.py) for some examples.

I hope this helps, and let me know if you have any other questions!

**Comment by ShaileshSridhar2403** [comment]
Great, thanks @gabrielilharco this helped a lot! I'll reach out to you again if I have other questions.
